USE w3schools;
-- ALTER TABLE : 테이블 변경

CREATE TABLE MyTable13 (
	Col1 INT,
    Col2 INT
);


-- 컬럼추가 ADD  COLUMN
ALTER TABLE MyTable13
ADD COLUMN col3 VARCHAR(10);
ALTER TABLE MyTable13
ADD COLUMN col4 DEC(10, 2);
-- 연습 MyTable13에 5번째 컬럼 추가
ALTER TABLE MyTable13
ADD COLUMN col5 INT;

-- 첫번째 컬럼으로 추가
ALTER TABLE MyTable13 ADD COLUMN col6 INT FIRST;
ALTER TABLE MyTable13 ADD COLUMN col7 INT FIRST;
DESC MyTable13;

-- 중간에 컬럼 추가
ALTER TABLE MyTable13 ADD COLUMN col8 VARCHAR(9) AFTER col7;

-- 연습) 첫번쨰 컬럼으로 하나 추가
ALTER TABLE MyTable13 ADD COLUMN col9 INT FIRST;
-- 연습 ) 컬럼을 중간에 추가
ALTER TABLE MyTable13 ADD COLUMN col10 INT AFTER col6;
DESC MyTable13;